name: basic_services

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version packages
version: 1.0.2+4

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # setup services ( null safety )
  stacked_services: ^0.8.7

  # flutter plugin for store data in secure storage. ( null safety )
  shared_preferences: ^2.0.6

  # permission service ( null safety )
  permission_handler: ^8.1.1

  # injection service ( null safety )
  get_it: ^7.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: false