name: xulu_services

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version packages
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # setup services
  stacked_services: ^0.7.2

  # http request handling ( null safety )
  dio: ^4.0.0-beta6

  # flutter plugin for store data in secure storage. ( null safety )
  flutter_secure_storage: ^4.0.0

  # permission service ( null safety  )
  permission_handler: ^6.0.1

  # injection service
  get_it: ^5.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true