name: xulu_services

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version packages
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # setup services ( null safety beta )
  stacked_services: ^0.8.0-nullsafety.1

  # http request handling ( null safety beta )
  dio: ^4.0.0-prev3

  # flutter plugin for store data in secure storage. ( null safety )
  flutter_secure_storage: ^4.1.0

  # permission service ( null safety  )
  permission_handler: ^6.1.1

  # injection service ( null safety  )
  get_it: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true