name: basic_services

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# Version packages
version: 1.0.1+3

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  # setup services ( null safety )
  stacked_services: ^0.8.6

  # flutter plugin for store data in secure storage. ( null safety )
  shared_preferences: ^2.0.5

  # permission service ( null safety )
  permission_handler: ^7.1.0

  # injection service ( null safety )
  get_it: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: false